version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/nextjs-calculator
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user


  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 60
      runas: root

  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: root
