version: '3.8'

services:
  nextjs-app:
    image: my-nextjs-app:latest
    build: .
    ports:
      - "3000:3000"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        max_replicas_per_node: 1  # Ensures at least one replica per node
    networks:
      - nextjs-net

networks:
  nextjs-net:
    driver: overlay
