version: "3.8"
services:
  nextjs-app:
    image: shraddha2566/nextjs-calculator:latest  # Make sure this matches your Docker Hub repo
    ports:
      - "3000:3000"
    deploy:
      replicas: 2
      restart_policy:
        condition: any
    networks:
      - nextjs-net

networks:
  nextjs-net:
    driver: overlay

