version: '3.8'

services:
  nextjs-app:
    image: my-nextjs-app:latest
    build: .
    ports:
      - "3000:3000"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 10s
      rollback_config:
        parallelism: 1
    networks:
      - nextjs-net

networks:
  nextjs-net:
    driver: overlay
