apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-calculator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
      - name: nextjs-calculator
        image: nextjs-calculator/nextjs-app:latest
        ports:
        - containerPort: 3000
