service: nextjs-calculator

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 800
  timeout: 30
  region: ca-central-1
  environment:
    NODE_ENV: production

plugins:
  - serverless-nextjs

functions:
  nextjs-app:
    handler: .serverless_nextjs/index.handler
    events:
      - httpApi: '*'

custom:
  serverless-nextjs:
    memory: 800
    timeout: 30
    name: nextjs-calculator
    bucketName: nextjs-calculator-deployment
