version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run:
          name: Deploy to EC2
          command: |
            tar --exclude='./deploy-package' -czf deploy.tar.gz .
            scp -o StrictHostKeyChecking=no deploy.tar.gz ubuntu@35.183.24.169:~/app
            ssh -o StrictHostKeyChecking=no ubuntu@35.183.24.169 "
              cd ~/app &&
              tar -xzf deploy.tar.gz &&
              rm deploy.tar.gz &&
              npm install --production &&
              pm2 restart all || pm2 start npm --name 'next-calculator' -- start
            "

workflows:
  version:

