version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run:
          name: Deploy to EC2
          command: |
            mkdir deploy-package
            cp -r * deploy-package
            scp -o StrictHostKeyChecking=no -r deploy-package/* ubuntu@35.183.24.169:~/app
            ssh -o StrictHostKeyChecking=no ubuntu@35.183.24.169 "
              cd ~/app &&
              npm install --production &&
              pm2 restart all || pm2 start npm --name 'next-calculator' -- start
            "

workflows:
  version: 2
  deploy_flow:
    jobs:
      - deploy

